"""The detect, verify, rank chain over the corpus with canned scouts and verdicts (spec 6, 11).

Scout and verdict files are the first live run's output (plus the hand edits the
phase 2 plan names); every deterministic stage is compared byte for byte to its
golden. Regenerate the deterministic goldens with UPDATE_GOLDENS=1 after an
intentional change; never regenerate the scouts or verdicts by hand.

The chain ends at the render: ``notes.json`` (the remediation agent's reply, the
one input on this chain no script produces) is hand-written per fixture and
copied into the workdir, then ``design.md`` and ``findings.json`` are compared
like every other stage. ``notes.json`` is an input, never regenerated by
UPDATE_GOLDENS; ``design.md`` and ``findings.json`` are outputs and are.

Three clocks are pinned so the goldens stay stable: ``run_patterns`` runs with
``blame=False`` (SATD ages are wall-clock), ``run_rules`` runs at ``RULES_NOW``,
and the render runs at ``SCAN_DATE``. The rule quotes for
``release.stale-env-branch`` and ``ownership.former-contributor`` spell an age in
days, and the fingerprint hashes that quote, so an unpinned clock would give the
same debt a new fingerprint every day; ``design.md`` prints its scan date twice,
so an unpinned render date would put today into the golden.

One finding per fixture (``PIN_TITLE``) is hand-added with a quote that is not in
the file, so the diversion path is exercised on every run. The live scouts of
their own accord produced a few more unverifiable quotes; those are named in
``LIVE_QUOTE_MISSES`` rather than edited out, so the test still states the exact
set of quotes that must fail.

The verdict goldens are the live output, redacted as the harness writes them:
``live_run._write_payload`` walks the array (verifier) contract through
``redaction.redact``, so ``service-py/verdicts/verify-02.json`` was re-redacted
once by hand to match (hand edit 4). The scout goldens are raw, as the harness
writes them: ``merge_findings`` verifies a quote against the file before it
redacts it, so a credential-shaped quote has to stay raw here to be found at all.
"""
from __future__ import annotations

import json
import os
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest
from apply_verdicts import apply
from baseline import diff
from concern_index import build_concern_index
from config import DEFAULTS
from design_parser import parse_design
from design_writer import load_inputs, write_design
from evaluate import evaluate
from inventory import build_all, write_json, write_outputs
from merge_findings import merge
from patterns import run_patterns
from plan_scan import build_plan, write_plan
from rank import rank
from rules import run_rules
from verify_prompts import build_verify_plan

GOLDEN = Path(__file__).parent / "golden"
CORPUS = Path(__file__).parent / "fixtures" / "corpus"
FIXTURES = ("service-py", "web-ts", "mixed-decoys")
UPDATE = os.environ.get("UPDATE_GOLDENS") == "1"
# The first live run's date: keeping it fixed keeps the day counts, and so the
# fingerprints, that rules.py derives from "now" identical on every later run.
RULES_NOW = datetime(2026, 9, 5, tzinfo=UTC)
# The render's own clock. ``design.md`` prints the scan date in its frontmatter and
# in the ``# Tech-debt scan - <date>`` header, so an unpinned ``date.today()`` would
# put today into every golden and break the byte comparison tomorrow.
SCAN_DATE = "2026-09-06"
# The hand-added finding whose quote is not in the file; the merge must divert it.
PIN_TITLE = "invented quote (golden pin)"
# Live scout findings that cite a quote ``find_quote`` cannot rejoin. The round-0
# misses all spanned more lines than the fallback window and were cited a line or
# two off; fix round 1 widened that window to the quote's own line count and every
# one of them rejoined. The one that remains is a different failure: the second
# web-ts run quoted ``getJson`` with an interior line (``return await
# response.json();``) silently dropped, and no window recovers a quote whose middle
# is missing. The tables are kept (empty where they are empty) so a new unverifiable
# quote fails the test rather than passing as noise. ``diverted`` findings lose every
# quote and land in ``open_questions``; ``partial`` findings keep another verified
# quote and stay as candidates.
LIVE_QUOTE_MISSES: dict[str, dict[str, frozenset[str]]] = {
    "service-py": {"diverted": frozenset(), "partial": frozenset()},
    "web-ts": {
        "diverted": frozenset({"API client silently swallows fetch errors with no test"}),
        "partial": frozenset(),
    },
    "mixed-decoys": {"diverted": frozenset(), "partial": frozenset()},
}
# Batches the plan asks for that no live run ever produced a verdict file for. A
# verdict cannot be written by hand (it would be invented agent output), so such a
# batch's candidates stay unverified at tier C. The table is empty: fix round 1
# recovered enough quotes to push web-ts into a fifth batch its first live run never
# made, and fix round 2's second web-ts run supplied that batch. Kept (empty) so a
# plan that outgrows its verdicts again fails here rather than passing silently.
UNVERIFIED_BATCHES: dict[str, frozenset[str]] = {
    "service-py": frozenset(),
    "web-ts": frozenset(),
    "mixed-decoys": frozenset(),
}

Chain = tuple[dict[str, Any], dict[str, Any], dict[str, Any]]


def _canon(doc: dict[str, Any], root: str) -> bytes:
    """The document as the golden holds it, with the temporary repository root masked.

    Both spellings are masked: the plain path and the JSON-escaped one a Windows
    root turns into (``C:\\repo`` is written ``C:\\\\repo`` inside a JSON string).
    """
    text = json.dumps(doc, indent=2) + "\n"
    text = text.replace(root.replace("\\", "\\\\"), "<root>").replace(root, "<root>")
    return text.encode("utf-8")


def _check(name: str, doc: dict[str, Any], golden: Path, root: str) -> None:
    got = _canon(doc, root)
    if UPDATE:
        golden.parent.mkdir(parents=True, exist_ok=True)
        golden.write_bytes(got)
    assert golden.is_file(), f"missing golden {golden}"
    assert got == golden.read_bytes(), f"{name} differs from {golden}"


def _check_text(name: str, text: str, golden: Path, root: str) -> None:
    """``_check``'s text twin: same UPDATE_GOLDENS behaviour, same root masking, LF only.

    ``render_design`` already joins its lines with a bare line feed, so the
    string is encoded as it stands and written with ``write_bytes``; nothing
    here may round-trip through text mode, or a Windows checkout would store
    CRLF and never match again.
    The repository root reaches ``design.md`` twice (the frontmatter ``root:``
    key and the ``Scanned `<root>`` header line) and is masked the same two ways
    ``_canon`` masks it, so one helper serves both document kinds.
    """
    masked = text.replace(root.replace("\\", "\\\\"), "<root>").replace(root, "<root>")
    got = masked.encode("utf-8")
    if UPDATE:
        golden.parent.mkdir(parents=True, exist_ok=True)
        golden.write_bytes(got)
    assert golden.is_file(), f"missing golden {golden}"
    assert got == golden.read_bytes(), f"{name} differs from {golden}"


def _chain(name: str, repo: Path, tmp_path: Path) -> Chain:
    workdir = tmp_path / "wd"
    planted = json.loads((CORPUS / name / "planted.json").read_bytes())
    inventory, coupling = build_all(
        repo, churn_months=int(planted["churn_months"]), config=DEFAULTS
    )
    write_outputs(inventory, coupling, workdir)
    # Step 1a (after inventory, before patterns): the concerns scout's definition-name
    # index. Built here, not left absent, so the concerns family's leads are real
    # ``candidate`` entries rather than an empty pool that skips the family outright.
    write_json(workdir / "concern-index.json", build_concern_index(repo, inventory, coupling))
    patterns, inline = run_patterns(repo, inventory, DEFAULTS, blame=False)
    for entry in inventory["files"]:
        entry["inline_disables"] = inline.get(entry["path"], 0)
    write_json(workdir / "inventory.json", inventory)
    write_json(workdir / "patterns.json", patterns)
    findings, leads = run_rules(repo, inventory, DEFAULTS, now=RULES_NOW)
    write_json(
        workdir / "rule-findings.json",
        {"schema_version": 2, "findings": findings, "leads": leads},
    )
    golden = GOLDEN / name
    # Step 4's canned counterpart: the golden tool-signals.json (test_tools_probe.py's
    # own live-probe golden for this fixture) copied into the workdir so an inference
    # signal on a planted file -- the ruff PERF401 hit on the performance family's
    # planted loop -- can earn a candidate the ``tool:`` corroboration token spec 2.3's
    # cap requires. No test-only signal is invented: every entry in this file is real
    # tool output, pinned by test_tools_probe.py against the same corpus files.
    shutil.copy(golden / "tool-signals.json", workdir / "tool-signals.json")
    plan, prompts = build_plan(workdir, DEFAULTS, families="deep", top=5)
    write_plan(workdir, plan, prompts)
    for entry in plan["entries"]:
        src = golden / entry["output"]
        assert src.is_file(), f"golden scout missing for {entry['family']} on {name}"
        dest = workdir / entry["output"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, dest)
    for extra in sorted((golden / "scouts").glob("*.json")):
        assert extra.name in {Path(e["output"]).name for e in plan["entries"]}, (
            f"golden scout {extra.name} is not in the plan for {name}"
        )
    root = str(repo.resolve())
    candidates = merge(workdir, repo, DEFAULTS)
    write_json(workdir / "candidates.json", candidates)
    _check("candidates", candidates, golden / "candidates.json", root)
    vplan, _ = build_verify_plan(workdir, repo, DEFAULTS, 5)
    _check("verify-plan", vplan, golden / "verify-plan.json", root)
    verdicts: dict[str, list[dict[str, Any]]] = {}
    for batch in vplan["batches"]:
        src = golden / batch["output"]
        if batch["output"] in UNVERIFIED_BATCHES[name]:
            assert not src.is_file(), f"{src} exists; drop it from UNVERIFIED_BATCHES"
            continue
        assert src.is_file(), f"golden verdict missing: {src}"
        verdicts[batch["output"]] = json.loads(src.read_bytes())
    verified = apply(candidates["candidates"], vplan, verdicts)
    # Persisted as well as compared, the way ``candidates.json`` already is: the
    # render stage below reads the whole chain back off disk through
    # ``load_inputs``, so a stage that only ever existed in memory is missing.
    write_json(workdir / "verified.json", verified)
    _check("verified", verified, golden / "verified.json", root)
    ranked = rank(verified, inventory, DEFAULTS, preset="balanced", top=5)
    write_json(workdir / "ranked.json", ranked)
    _check("ranked", ranked, golden / "ranked.json", root)
    # No fixture has a baseline yet (phase 5's ``record`` is Task 3), so every
    # status is NEW and ``baseline_found`` is false -- the point of this golden
    # is that the chain now produces the file ``design_writer`` has been
    # waiting for, not that it changes any classification.
    diff_doc = diff(verified, None, repo, SCAN_DATE)
    write_json(workdir / "diff.json", diff_doc)
    _check("diff", diff_doc, golden / "diff.json", root)
    # The render stage. ``notes.json`` is the one input on this chain that no
    # script produces: it is the remediation agent's reply, so it is hand-written
    # per fixture and copied in exactly as a real run would drop it in the
    # workdir. web-ts deliberately omits its last top-N fingerprint, so the
    # NOTE_PLACEHOLDER path is covered by a real golden rather than a unit stub.
    shutil.copy(golden / "notes.json", workdir / "notes.json")
    write_design(load_inputs(workdir), SCAN_DATE, workdir / "design.md")
    _check_text(
        "design.md",
        (workdir / "design.md").read_bytes().decode("utf-8"),
        golden / "design.md",
        root,
    )
    # findings.json lands in the workdir, never beside --out; that is the contract
    # evaluate.load_findings depends on, so reading it from anywhere else here
    # would let a regression in write_design pass unnoticed.
    _check(
        "findings.json",
        json.loads((workdir / "findings.json").read_bytes()),
        golden / "findings.json",
        root,
    )
    return candidates, verified, ranked


@pytest.mark.parametrize("name", FIXTURES)
def test_chain_matches_goldens_and_meets_the_corpus_bar(
    name: str, request: pytest.FixtureRequest, tmp_path: Path
) -> None:
    repo = request.getfixturevalue(name.replace("-", "_") + "_repo")
    candidates, verified, ranked = _chain(name, repo, tmp_path)
    planted = json.loads((CORPUS / name / "planted.json").read_bytes())
    report = evaluate(verified["findings"], planted, set(ranked["top_n"]), top=5)
    assert report["decoys_in_tier_a"] == 0, report["decoys"]
    assert report["decoys_in_top_n"] == 0, report["decoys"]
    assert report["counts"]["on_planted"] > 0
    diverted = sorted(
        q["question"] for q in candidates["open_questions"] if q["reason"] == "quote not found"
    )
    assert diverted == sorted({PIN_TITLE, *LIVE_QUOTE_MISSES[name]["diverted"]}), diverted
    assert any(f["verdict"] == "reject" and f["trap_matched"] for f in verified["findings"])
    top_n = set(ranked["top_n"])
    assert all(
        f["tier"] in ("A", "B") for f in verified["findings"] if f["fingerprint"] in top_n
    )

    # The rendered document reads back through its own parser on real data.
    workdir = tmp_path / "wd"
    design = workdir / "design.md"
    parsed = parse_design(design)
    assert parsed["metadata"]["schema_version"] == 2
    top_slugs = [f["slug"] for f in parsed["findings"] if f["tier"] in ("A", "B")]
    assert top_slugs and len(top_slugs) == len(set(top_slugs)), "slugs are unique"
    for finding in parsed["findings"]:
        assert finding["category"] == finding["family"]
        assert "# Not assessed" not in finding["body_md"], "the H1 boundary holds on real data"
    # Only a top-N finding gets a Signals section; below-the-cut ones are compact.
    assert set(ranked["top_n"]) >= {
        f["fingerprint"] for f in parsed["findings"] if "### Signals" in f["body_md"]
    }
    # Nothing in the render reads a clock or a random seed of its own: the same
    # workdir at the same pinned scan date renders byte for byte the same document.
    again = tmp_path / "again" / "design.md"
    write_design(load_inputs(workdir), SCAN_DATE, again)
    assert again.read_bytes() == design.read_bytes(), "the render is deterministic"


@pytest.mark.parametrize("name", FIXTURES)
def test_every_golden_quote_except_the_pin_verifies(
    name: str, request: pytest.FixtureRequest
) -> None:
    """Only the pin and the named live misses fail ``find_quote`` against the fixture."""
    from evidence import find_quote
    from merge_findings import _normalise_path

    repo = request.getfixturevalue(name.replace("-", "_") + "_repo")
    diverted: set[str] = set()
    partial: set[str] = set()
    for scout in sorted((GOLDEN / name / "scouts").glob("*.json")):
        for finding in json.loads(scout.read_bytes())["findings"]:
            found = []
            for ev in finding["evidence"]:
                # merge_findings normalises backslashes to forward slashes before
                # verifying a quote, so a golden scout recorded on Windows (a
                # literal "vendor\\x.js") must be resolved the same way here, or
                # the path is read as one Linux filename that never exists.
                path = repo / (_normalise_path(ev["file"]) or ev["file"])
                raw = path.read_bytes() if path.is_file() else b""
                lines = raw.decode("utf-8", "replace").splitlines()
                hit = find_quote(lines, ev["quote"], ev.get("line_start"), ev.get("line_end"))
                found.append(hit is not None)
            if not any(found):
                diverted.add(finding["title"])
            elif not all(found):
                partial.add(finding["title"])
    expected = LIVE_QUOTE_MISSES[name]
    assert diverted == {PIN_TITLE, *expected["diverted"]}, sorted(diverted)
    assert partial == set(expected["partial"]), sorted(partial)


# --- the fact-class producer golden (task 6, spec 4.7) --------------------------------

TOOL_SIGNALS = Path(__file__).parent / "fixtures" / "tool-signals" / "osv-and-friends.json"
TOOL_CHAIN_GOLDEN = GOLDEN / "tool-chain"


@pytest.fixture(scope="session")
def _tool_chain_result(
    service_py_repo: Path, tmp_path_factory: pytest.TempPathFactory
) -> dict[str, Any]:
    """``merge``, ``verify_prompts.build_verify_plan`` and ``apply``, run once over
    service-py with ``osv-and-friends.json`` written into the workdir as
    ``tool-signals.json`` -- task 6's proof that the fact-class producer route (spec
    4.5, 4.7) reaches a tier through the real disk-read chain ``merge()`` uses in
    production, not merely through ``tool_candidates`` called directly the way
    ``test_merge_findings.TestTierProducerInvariant`` does, and that nothing else
    reaching this same run acquires one. osv-scanner cannot be installed on this
    machine, so this hand-written signals file is the only way to prove that path end
    to end.

    This is its own golden set (``golden/tool-chain/``), not a fourth entry in
    ``FIXTURES``: the three corpus fixtures' chains stay exactly as
    ``test_chain_matches_goldens_and_meets_the_corpus_bar`` already pins them, with no
    ``tool-signals.json`` in their workdirs, so service-py's own
    inventory/patterns/rules/scouts are replayed a second time here rather than
    reusing or perturbing that fixture's run.

    Session-scoped: every ``TestToolChainGolden`` assertion reads this one run rather
    than each re-driving the chain itself. ``apply`` is driven with no verdicts at
    all (an empty dict): this golden's scope stops at the producer set and the
    selection it does or doesn't reach (``candidates.json``, ``verify-plan.json``),
    not the verifier-confirm pipeline that would let a tool token move a capped
    family's tier -- that effect is already pinned directly against
    ``apply_verdicts.family_cap`` by ``TestToolTokenLiftsTheCap`` in
    test_merge_findings.py, and against real verifier replies by the three corpus
    goldens above.
    """
    repo = service_py_repo
    workdir = tmp_path_factory.mktemp("tool-chain") / "wd"
    planted = json.loads((CORPUS / "service-py" / "planted.json").read_bytes())
    inventory, coupling = build_all(
        repo, churn_months=int(planted["churn_months"]), config=DEFAULTS
    )
    write_outputs(inventory, coupling, workdir)
    patterns, inline = run_patterns(repo, inventory, DEFAULTS, blame=False)
    for entry in inventory["files"]:
        entry["inline_disables"] = inline.get(entry["path"], 0)
    write_json(workdir / "inventory.json", inventory)
    write_json(workdir / "patterns.json", patterns)
    findings, leads = run_rules(repo, inventory, DEFAULTS, now=RULES_NOW)
    write_json(
        workdir / "rule-findings.json",
        {"schema_version": 2, "findings": findings, "leads": leads},
    )
    plan, prompts = build_plan(workdir, DEFAULTS, families="deep", top=5)
    write_plan(workdir, plan, prompts)
    # service-py's own golden scouts, replayed as a real run's scouts would produce
    # them: the jscpd signal below corroborates the one duplication finding they
    # raise, and the pool the two new fact-class candidates join is sized against
    # them (28 scout candidates; see the docstring above).
    golden_scouts = GOLDEN / "service-py"
    for entry in plan["entries"]:
        src = golden_scouts / entry["output"]
        dest = workdir / entry["output"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, dest)
    write_json(workdir / "tool-signals.json", json.loads(TOOL_SIGNALS.read_bytes()))
    root = str(repo.resolve())
    candidates = merge(workdir, repo, DEFAULTS)
    write_json(workdir / "candidates.json", candidates)
    _check("tool-chain candidates", candidates, TOOL_CHAIN_GOLDEN / "candidates.json", root)
    vplan, _ = build_verify_plan(workdir, repo, DEFAULTS, 5)
    _check("tool-chain verify-plan", vplan, TOOL_CHAIN_GOLDEN / "verify-plan.json", root)
    verified = apply(candidates["candidates"], vplan, {})
    write_json(workdir / "verified.json", verified)
    _check("tool-chain verified", verified, TOOL_CHAIN_GOLDEN / "verified.json", root)
    ranked = rank(verified, inventory, DEFAULTS, preset="balanced", top=5)
    write_json(workdir / "ranked.json", ranked)
    _check("tool-chain ranked", ranked, TOOL_CHAIN_GOLDEN / "ranked.json", root)
    return {"candidates": candidates, "vplan": vplan, "verified": verified, "ranked": ranked}


class TestToolChainGolden:
    """Spec 4.7's negative half, proved through the real chain rather than a canned
    dispatch (task 6): an osv-scanner advisory reaches tier A with no verifier ever
    reading it, a gitleaks secret reaches the verifier's selection instead of
    skipping it, and -- the half that matters -- every other candidate this run
    raises (28 scout candidates, 9 rule findings, and this run's own gitleaks and
    hadolint candidates) still does not acquire a tier outside that one route.
    """

    @pytest.fixture(autouse=True)
    def _bind(self, _tool_chain_result: dict[str, Any]) -> None:
        self.candidates = _tool_chain_result["candidates"]["candidates"]
        self.vplan = _tool_chain_result["vplan"]
        self.verified = _tool_chain_result["verified"]

    def _candidates_with_tool_signals(self) -> list[dict[str, Any]]:
        return self.candidates

    def _chain_with_tool_signals(self) -> dict[str, Any]:
        return self.verified

    def _verified_fingerprints(self) -> set[str]:
        """The fingerprints ``verify_prompts`` selected for a verifier's attention."""
        return set(self.vplan["selected"])

    def test_the_osv_fact_is_tier_A_with_no_verdict(self) -> None:
        verified = self._chain_with_tool_signals()
        osv = next(f for f in verified["findings"] if f["source"] == "tool"
                   and "tool:osv-scanner" in f["confirmed_by"])
        assert osv["tier"] == "A"
        assert osv["verdict"] == "rule"
        assert osv["fingerprint"] not in self._verified_fingerprints()

    def test_no_other_candidate_class_skips_verification(self) -> None:
        candidates = self._candidates_with_tool_signals()
        for cand in candidates:
            if cand.get("tier") is not None:
                assert cand["source"] in {"rule", "tool"}
                if cand["source"] == "tool":
                    assert "tool:osv-scanner" in cand["confirmed_by"]

    def test_the_gitleaks_fact_is_sent_to_the_verifier(self) -> None:
        """Not found by ``"tool:gitleaks" in confirmed_by``: the untiered fact routes
        deliberately raise with an *empty* ``confirmed_by`` (spec 4.5 --
        ``merge_findings.tool_candidates``'s docstring: a self-reported
        ``tool:<name>`` token here would read as independent corroboration of the
        very thing that raised it), so no candidate in this run ever carries the
        literal token ``"tool:gitleaks"``. The gitleaks candidate is instead the
        run's one ``source: "tool"``, ``family: "security"`` candidate -- unique,
        since gitleaks is the only fact-class tool security names."""
        candidates = self._candidates_with_tool_signals()
        leak = next(c for c in candidates if c["source"] == "tool" and c["family"] == "security")
        assert leak["tier"] is None
        assert leak["confirmed_by"] == []

    def test_the_gitleaks_candidate_is_selected_not_skipped(self) -> None:
        """The bypass this golden exists to check has two halves: an osv fact must
        skip the verifier (above), and an ordinary untiered candidate must not. The
        brief's original three assertions drive only ``merge``/``apply``/``rank`` and
        cannot see this half -- it is decided in ``verify-plan.json``, by
        ``select_candidates`` pooling only ``tier is None`` candidates."""
        candidates = self._candidates_with_tool_signals()
        leak = next(c for c in candidates if c["source"] == "tool" and c["family"] == "security")
        assert leak["fingerprint"] in self._verified_fingerprints()
        assert leak["fingerprint"] not in self.vplan["unverified"]

    def test_the_hadolint_fact_on_an_uncovered_file_becomes_its_own_untiered_candidate(
        self,
    ) -> None:
        """Every hadolint/actionlint fact ``test_merge_findings``'s producer-invariant
        fixture feeds through the real service-py corpus lands on a file a rule
        finding already covers (the fixture's one Dockerfile), so it only ever
        exercises the merge-into-rule branch there. README.md has no pipeline-infra
        rule finding, so this is the first real-chain proof of the other branch: an
        uncovered fact raises its own candidate, source ``"tool"``, tier ``None``,
        with the same empty ``confirmed_by`` the gitleaks route uses."""
        candidates = self._candidates_with_tool_signals()
        hadolint = next(
            c for c in candidates if c["source"] == "tool" and c["family"] == "pipeline-infra"
        )
        assert hadolint["tier"] is None
        assert hadolint["confirmed_by"] == []
        assert hadolint["evidence"][0]["file"] == "README.md"

    def test_the_jscpd_signal_corroborates_the_duplication_candidate(self) -> None:
        """The signal targets ``src/pay/ledger.py``, the *second* evidence item on
        the fixture's one duplication candidate (whose primary evidence is
        ``src/pay/refund.py``): a corroboration match that only checked a candidate's
        primary evidence file would silently miss it here."""
        candidates = self._candidates_with_tool_signals()
        dup = next(
            c for c in candidates if c["family"] == "duplication" and c["source"] == "scout"
        )
        assert "tool:jscpd" in dup["confirmed_by"]

    def test_an_inference_signal_for_a_family_with_no_candidate_corroborates_nothing(
        self,
    ) -> None:
        """The lizard signal names ``complex-units`` (zero candidates anywhere in
        this fixture) on ``src/pay/refund.py`` -- a file several *other* families'
        scout candidates do cite. If corroboration ever matched on file alone,
        dropping the family check, ``tool:lizard`` would leak onto one of them."""
        candidates = self._candidates_with_tool_signals()
        assert not any("tool:lizard" in c["confirmed_by"] for c in candidates)
